import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createWriteStream } from "node:fs";
import { pipeline } from "node:stream/promises";
import type { MultipartFile } from "@fastify/multipart";

// ─── Storage ──────────────────────────────────────────────────────────────────

export const UPLOADS_DIR = process.env.UPLOADS_DIR ?? path.join(process.cwd(), "uploads");

export async function ensureUploadsDir() {
  await fs.mkdir(UPLOADS_DIR, { recursive: true });
}

/** Save a multipart file to disk, return the saved file path and byte size. */
export async function saveUploadedFile(
  part: MultipartFile,
  filename: string
): Promise<{ filePath: string; fileSize: number }> {
  const filePath = path.join(UPLOADS_DIR, filename);
  await pipeline(part.file, createWriteStream(filePath));
  const stat = await fs.stat(filePath);
  return { filePath, fileSize: stat.size };
}

/** Delete a file from disk (silently ignores if missing). */
export async function deleteFile(filePath: string): Promise<void> {
  try {
    await fs.unlink(filePath);
  } catch {
    // already gone — fine
  }
}

// ─── Text extraction ──────────────────────────────────────────────────────────

export interface ExtractResult {
  text: string;
  pageCount: number;
}

export async function extractText(
  filePath: string,
  mimeType: string
): Promise<ExtractResult> {
  if (mimeType === "application/pdf") {
    return extractPdf(filePath);
  }
  if (
    mimeType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
    mimeType === "application/msword"
  ) {
    return extractDocx(filePath);
  }
  throw new Error(`Unsupported file type: ${mimeType}`);
}

async function extractPdf(filePath: string): Promise<ExtractResult> {
  // pdf-parse is a CJS module — use createRequire for clean interop in ESM
  const { createRequire } = await import("node:module");
  const require = createRequire(import.meta.url);
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const pdfParse = require("pdf-parse") as (buf: Buffer) => Promise<{ text: string; numpages: number }>;
  const buffer = await fs.readFile(filePath);
  const data = await pdfParse(buffer);
  return { text: data.text, pageCount: data.numpages };
}

async function extractDocx(filePath: string): Promise<ExtractResult> {
  const mammoth = await import("mammoth");
  const result = await mammoth.extractRawText({ path: filePath });
  // DOCX doesn't expose page count reliably — estimate ~400 words/page
  const wordCount = result.value.split(/\s+/).length;
  const pageCount = Math.max(1, Math.ceil(wordCount / 400));
  return { text: result.value, pageCount };
}

// ─── PDF export ───────────────────────────────────────────────────────────────

import PDFDocument from "pdfkit";
import type { Brief } from "@prisma/client";

export async function generateBriefPdf(
  originalName: string,
  brief: Brief & { redFlags: string[]; recommendedActions: string[] }
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("DocuNova AI — Contract Brief", { align: "center" });
    doc.moveDown(0.5);
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#555")
      .text(`Document: ${originalName}`, { align: "center" });
    doc.moveDown(1.5);

    const section = (label: string, value: string | null | undefined) => {
      if (!value) return;
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#000").text(label);
      doc.fontSize(11).font("Helvetica").fillColor("#333").text(value, { indent: 10 });
      doc.moveDown(0.8);
    };

    const listSection = (label: string, items: string[]) => {
      if (!items.length) return;
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#000").text(label);
      for (const item of items) {
        doc
          .fontSize(11)
          .font("Helvetica")
          .fillColor("#333")
          .text(`• ${item}`, { indent: 10 });
      }
      doc.moveDown(0.8);
    };

    section("Parties", brief.parties);
    section("Effective Date", brief.effectiveDate);
    section("Obligations", brief.obligations);
    section("Payment Terms", brief.payment);
    section("Penalties", brief.penalties);
    section("Renewal Terms", brief.renewalTerms);
    listSection("Red Flags", brief.redFlags);
    listSection("Recommended Actions", brief.recommendedActions);

    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#aaa")
      .text(
        "Generated by DocuNova AI. This is not legal advice. Consult a qualified attorney for legal guidance.",
        { align: "center" }
      );

    doc.end();
  });
}
